resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: cicd-test2/npm-cache-resource
      tag: latest
resources:
  - name: cicd-test2
    type: git
    source: &repo-source
      uri: https://github.com/goodjen/cicd-test2
      branch: master
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json
jobs:
  - name: Install dependencies
    plan:
      - get: cicd-test2
        trigger: true
      - get: dependency-cache
  - name: Run tests
    plan:
      - get: cicd-test2
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]
      - task: run the test suite
        file: cicd-test2/ci/tasks/run_tests.yml

